:step: 0
:source-highlighter: highlightjs
:sourcedir: src/
:imagesdir: images/

:toc:
:toc-title: Table des matières

= Project DAWIN

Deadline :

* DAWIN : 16/02/2020

== Spécifications

=== Fonctionnalités

* Ajout, suppression et édition des informations d'un film
* Affichage de la liste des films
* Recherche à l'intérieur des différents paramètres (un seul champ de recherche pour rechercher l'année, le titre, le réalisateur)
* Pouvoir mettre l'url du poster du film
* Possibilité de noter un film sur une échelle de 1 à 5
* Les pages doivent posséder un style CSS

=== Librairie conseillées

* Vous trouverez beaucoup de composants ici qui pourront vous permettre d'améliorer facilement l'interface : https://github.com/vuejs/awesome-vue#ui-components
* Vuetify pour l'interface

=== Objet Film

Voilà les informations de base qui doivent être contenues dans un film (hors notation et image) :

* Titre
* Année de sortie
* Langue
* Réalisateur
    ** Nom / Prénom
    ** Nationalité
    ** Date de naissance
* Genre du film (Science-Fiction, Historique etc...)

=== Structure des pages

```text
/ -> Liste des films avec recherche
/movie/:id -> Détails d'un film (avec lien vers édition, suppression, notation)
/movie/:id/edit -> Modification d'un film
```

=== Pré-requis

Le projet doit se lancer avec la commande :

```shell
$ npm install && npm run serve
```

== Notation

Plusieurs critères seront pris en compte pour la notation :

* Présence des fonctionnalités demandées
* Clarté du code
* Respect des différents concepts Vue.js (découpage en composants, variables computed etc...)

N'hésitez pas à me solliciter par email si vous avez des questions ou si vous êtes bloqués ! (cleriotsimon@gmail.com)